name: Create a new feature request
title: "[Feature]: description"
description: describe the feature here
type: feature
projects: "Sigmapitech/9"
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
      placeholder: "ex: Add new button to the homepage."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        ex:
        - Possible implementation ideas
        - Resources
        - Screenshots
        - Any other relevant information.
  - type: checkboxes
    attributes:
      label: Pre-submission checklist
      description: "Please ensure you have completed the following before submitting your feature request:"
      options:
        - label: I have set the apropriate label
          required: true
        - label: I have set the apropriate milestone
          required: true
    validations:
      required: true
