name: Create a refactor request
title: "Quick description"
description: request a refactor here
projects: "Sigmapitech/9"
body:
  - type: textarea
    id: refactor_description
    attributes:
      label: Describe the refactor
      description: A clear and concise description of what the refactor is.
      placeholder: "ex: Modify the button component for better accessibility."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        ex:
        - Possible implementation ideas
        - Resources
        - Screenshots
        - Any other relevant information.
  - type: checkboxes
    attributes:
      label: Pre-submission checklist
      description: "Please ensure you have completed the following before submitting your feature request:"
      options:
        - label: I have SET the apropriate label
          required: true
        - label: I have UNSET the issue tag
          required: true
        - label: I have SET the AREA project
          required: true
        - label: I have SET the apropriate milestone
          required: true
    validations:
      required: true
