name: Lint

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Run linters
        run: |
          nix-shell -p biome black --run "bash <<'EOF'
          set -o pipefail

          echo Running Biome...
          biome check .

          echo Running Black...
          black --check .

          if ! biome check . || ! black --check .; then
              echo 'One or more linters failed.'
              exit 1
          fi
          EOF
          "
